services:
  # Backend API Service
  - type: web
    name: partay-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend/src && uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: partay-db
          property: connectionString
      - key: API_HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://partay-frontend.onrender.com
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src/backend/src

  # Frontend Static Site
  - type: web
    name: partay-frontend
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://partay-backend.onrender.com

databases:
  - name: partay-db
    databaseName: partay_rentals
    plan: free
    region: oregon
