"""Initial migration with all 9 tables

Revision ID: 20f88b106586
Revises: 
Create Date: 2025-10-23 14:11:25.511322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f88b106586'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('address_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_name'), 'drivers', ['name'], unique=False)
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('address_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('address_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_time_window', sa.String(length=50), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_time_window', sa.String(length=50), nullable=True),
    sa.Column('rental_days', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('delivery_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('setup_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_driver_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_driver_id', sa.String(length=36), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['pickup_driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_assigned_driver_id'), 'bookings', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_delivery_date'), 'bookings', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_bookings_order_number'), 'bookings', ['order_number'], unique=True)
    op.create_index(op.f('ix_bookings_pickup_date'), 'bookings', ['pickup_date'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('inventory_items',
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requires_power', sa.Boolean(), nullable=False),
    sa.Column('min_space_sqft', sa.Integer(), nullable=True),
    sa.Column('allowed_surfaces', sa.Text(), nullable=True),
    sa.Column('default_warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('current_warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('inventory_item_id')
    )
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_table('booking_items',
    sa.Column('booking_item_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pickup_warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('return_warehouse_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.inventory_item_id'], ),
    sa.ForeignKeyConstraint(['pickup_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.ForeignKeyConstraint(['return_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('booking_item_id')
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_items_inventory_item_id'), 'booking_items', ['inventory_item_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('inventory_movement_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('from_location_type', sa.String(length=20), nullable=False),
    sa.Column('from_location_id', sa.String(length=36), nullable=True),
    sa.Column('to_location_type', sa.String(length=20), nullable=False),
    sa.Column('to_location_id', sa.String(length=36), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.inventory_item_id'], ),
    sa.PrimaryKeyConstraint('inventory_movement_id')
    )
    op.create_index(op.f('ix_inventory_movements_booking_id'), 'inventory_movements', ['booking_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_driver_id'), 'inventory_movements', ['driver_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_date'), 'inventory_movements', ['movement_date'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_booking_id'), 'notifications', ['booking_id'], unique=False)
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_booking_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inventory_movements_movement_date'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_driver_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_booking_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_booking_items_inventory_item_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pickup_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_order_number'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_delivery_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_assigned_driver_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
